title: My CV
owner: Karananou Peristera
email: p18kara4@ionio.gr
description: Karananou Peristera    My CV
baseurl: "" # the subpath of your site, e.g. /blog
url: " https://perikarananou.github.io/ " 
language: Native Greek
github_username: perikarananou
# Build settings
markdown: kramdown
theme: minima

permalink: pretty

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
excerpt_separator: <!--more-->
